package net.huray.solfit.bluetooth.util

// Connection STATE
const val STATE_DISCONNECTED = 0
const val STATE_CONNECTED = 1
const val STATE_SERVICE_DISCOVERED = 2
const val STATE_INDICATION_SUCCESS = 3
const val STATE_CONNECTING = 4
const val STATE_TIME_OUT = 5
const val STATE_ERROR = 6

// SCAN STATE
const val STATE_FAIL = 0
const val STATE_SCANNING = 1
const val STATE_STOPPED = 2

// GET WEIGHT STATE
const val STATE_GET_WEIGHT_START = 0
const val STATE_GET_WEIGHT_WAITING = 1
const val STATE_GET_WEIGHT_SUCCESS = 2

// GET BODY COMPOSITION STATE
const val STATE_GET_BODY_COMPOSITION_START = 20
const val STATE_GET_BODY_COMPOSITION_FAIL = 21
const val STATE_GET_BODY_COMPOSITION_SUCCESS = 22
